/**
 * defaultChartOfAccounts.js
 * شجرة الحسابات القياسية المعتمدة لمجموعة الصيدليات وشركات توزيع الأدوية
 * متوافقة مع المعايير المحاسبية IFRS ومحرك القيود المزدوجة ومراكز التكلفة
 */

export const DEFAULT_CHART_OF_ACCOUNTS = [
  // ── 1. الأصول (Assets) ──────────────────────────────────────────────────
  {
    id: 'acc-1',
    code: '1',
    name_ar: 'الأصول',
    name_en: 'Assets',
    account_type: 'asset',
    nature: 'debit',
    parent_id: null,
    level: 1,
    is_parent: true,
    is_system: true,
  },
  // 11 الأصول المتداولة
  {
    id: 'acc-11',
    code: '11',
    name_ar: 'الأصول المتداولة',
    name_en: 'Current Assets',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-1',
    level: 2,
    is_parent: true,
    is_system: true,
  },
  // 111 النقدية والخزائن
  {
    id: 'acc-111',
    code: '111',
    name_ar: 'النقدية بالصندوق والخزائن',
    name_en: 'Cash in Hand & Treasuries',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-11',
    level: 3,
    is_parent: true,
    is_system: true,
  },
  {
    id: 'acc-11101',
    code: '11101',
    name_ar: 'خزينة الإدارة الرئيسية',
    name_en: 'Main Treasury',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-111',
    level: 4,
    is_parent: false,
    opening_balance: 0,
    current_balance: 0,
  },
  {
    id: 'acc-11102',
    code: '11102',
    name_ar: 'خزينة صيدلية سموحة',
    name_en: 'Semouha Pharmacy Cashbox',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-111',
    level: 4,
    is_parent: false,
    opening_balance: 0,
    current_balance: 0,
  },
  {
    id: 'acc-11103',
    code: '11103',
    name_ar: 'خزينة صيدلية العجمي',
    name_en: 'Agami Pharmacy Cashbox',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-111',
    level: 4,
    is_parent: false,
    opening_balance: 0,
    current_balance: 0,
  },
  {
    id: 'acc-11104',
    code: '11104',
    name_ar: 'خزينة صيدلية محطة الرمل',
    name_en: 'Raml Station Pharmacy Cashbox',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-111',
    level: 4,
    is_parent: false,
    opening_balance: 0,
    current_balance: 0,
  },

  // 112 البنوك والحسابات المصرفية
  {
    id: 'acc-112',
    code: '112',
    name_ar: 'البنوك والحسابات الجارية',
    name_en: 'Bank Accounts',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-11',
    level: 3,
    is_parent: true,
    is_system: true,
  },
  {
    id: 'acc-11201',
    code: '11201',
    name_ar: 'البنك الأهلي المصري (حساب رئيسي)',
    name_en: 'National Bank of Egypt (NBE)',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-112',
    level: 4,
    is_parent: false,
    opening_balance: 0,
    current_balance: 0,
  },
  {
    id: 'acc-11202',
    code: '11202',
    name_ar: 'بنك مصر (حساب المعاملات)',
    name_en: 'Banque Misr',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-112',
    level: 4,
    is_parent: false,
    opening_balance: 0,
    current_balance: 0,
  },
  {
    id: 'acc-11203',
    code: '11203',
    name_ar: 'البنك التجاري الدولي (CIB)',
    name_en: 'Commercial International Bank (CIB)',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-112',
    level: 4,
    is_parent: false,
    opening_balance: 0,
    current_balance: 0,
  },

  // 113 وسائل الدفع الإلكتروني والمحافظ والتحويل اللحظي
  {
    id: 'acc-113',
    code: '113',
    name_ar: 'وسائل الدفع الإلكتروني ونقاط البيع والمحافظ',
    name_en: 'Electronic Payment Gateways & Wallets',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-11',
    level: 3,
    is_parent: true,
    is_system: true,
  },
  {
    id: 'acc-11301',
    code: '11301',
    name_ar: 'أجهزة نقاط البيع الإلكترونية (POS Visa/Mastercard)',
    name_en: 'POS Terminals (Cards)',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-113',
    level: 4,
    is_parent: false,
    opening_balance: 0,
    current_balance: 0,
  },
  {
    id: 'acc-11302',
    code: '11302',
    name_ar: 'شبكة التحويل اللحظي (Instapay)',
    name_en: 'Instapay Network',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-113',
    level: 4,
    is_parent: false,
    opening_balance: 0,
    current_balance: 0,
  },
  {
    id: 'acc-11303',
    code: '11303',
    name_ar: 'المحافظ الإلكترونية الذكية (فودافون كاش / أورنج / اتصالات / WE)',
    name_en: 'Mobile Wallets (Vodafone Cash, etc.)',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-113',
    level: 4,
    is_parent: false,
    opening_balance: 0,
    current_balance: 0,
  },

  // 114 العملاء والمدينون
  {
    id: 'acc-114',
    code: '114',
    name_ar: 'العملاء والمدينون وحسابات التأمين',
    name_en: 'Accounts Receivable & Insurance',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-11',
    level: 3,
    is_parent: true,
    is_system: true,
  },
  {
    id: 'acc-11401',
    code: '11401',
    name_ar: 'عملاء البيع الآجل (أفراد)',
    name_en: 'Credit Customers (Individuals)',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-114',
    level: 4,
    is_parent: false,
  },
  {
    id: 'acc-11402',
    code: '11402',
    name_ar: 'شركات التأمين الطبي (Medical Insurance TPA)',
    name_en: 'Medical Insurance Companies',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-114',
    level: 4,
    is_parent: false,
  },
  {
    id: 'acc-11403',
    code: '11403',
    name_ar: 'شركات ومؤسسات متعاقدة',
    name_en: 'Corporate Contracts',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-114',
    level: 4,
    is_parent: false,
  },

  // 115 المخزون السلعي
  {
    id: 'acc-115',
    code: '115',
    name_ar: 'المخزون السلعي (بضاعة الصيدليات)',
    name_en: 'Inventory',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-11',
    level: 3,
    is_parent: true,
    is_system: true,
  },
  {
    id: 'acc-11501',
    code: '11501',
    name_ar: 'مخزون الأدوية البشرية',
    name_en: 'Medicines Inventory',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-115',
    level: 4,
    is_parent: false,
    opening_balance: 0,
    current_balance: 0,
  },
  {
    id: 'acc-11502',
    code: '11502',
    name_ar: 'مخزون مستحضرات التجميل والعناية بالبشرة',
    name_en: 'Cosmetics & Skincare Inventory',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-115',
    level: 4,
    is_parent: false,
    opening_balance: 0,
    current_balance: 0,
  },
  {
    id: 'acc-11503',
    code: '11503',
    name_ar: 'مخزون المكملات الغذائية والفيتامينات',
    name_en: 'Supplements & Vitamins Inventory',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-115',
    level: 4,
    is_parent: false,
    opening_balance: 0,
    current_balance: 0,
  },
  {
    id: 'acc-11504',
    code: '11504',
    name_ar: 'مخزون المستلزمات والأجهزة الطبية',
    name_en: 'Medical Supplies & Devices Inventory',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-115',
    level: 4,
    is_parent: false,
    opening_balance: 0,
    current_balance: 0,
  },

  // 116 أرصدة مدينة أخرى ومصروفات مدفوعة مقدماً
  {
    id: 'acc-116',
    code: '116',
    name_ar: 'أرصدة مدينة أخرى ومصروفات مدفوعة مقدماً',
    name_en: 'Other Receivables & Prepayments',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-11',
    level: 3,
    is_parent: true,
  },
  {
    id: 'acc-11601',
    code: '11601',
    name_ar: 'سلف العاملين المؤقتة والمستديمة',
    name_en: 'Employee Advances & Loans',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-116',
    level: 4,
    is_parent: false,
  },
  {
    id: 'acc-11602',
    code: '11602',
    name_ar: 'إيجارات مقرات مدفوعة مقدماً',
    name_en: 'Prepaid Rent',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-116',
    level: 4,
    is_parent: false,
  },
  {
    id: 'acc-11603',
    code: '11603',
    name_ar: 'تأمينات مستردة لدى الغير (مرافق ومقار)',
    name_en: 'Refundable Utility Deposits',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-116',
    level: 4,
    is_parent: false,
  },

  // 12 الأصول الثابتة
  {
    id: 'acc-12',
    code: '12',
    name_ar: 'الأصول الثابتة',
    name_en: 'Fixed Assets',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-1',
    level: 2,
    is_parent: true,
    is_system: true,
  },
  {
    id: 'acc-121',
    code: '121',
    name_ar: 'الأثاث والديكورات والتجهيزات الصيدلانية',
    name_en: 'Furniture & Fixtures',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-12',
    level: 3,
    is_parent: false,
  },
  {
    id: 'acc-122',
    code: '122',
    name_ar: 'أجهزة الحاسب الآلي والشبكات ونقاط البيع',
    name_en: 'Computers & Network Hardware',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-12',
    level: 3,
    is_parent: false,
  },
  {
    id: 'acc-123',
    code: '123',
    name_ar: 'ثلاجات حفظ الأدوية والمكيفات والمولدات',
    name_en: 'Refrigeration & Cooling Equipment',
    account_type: 'asset',
    nature: 'debit',
    parent_id: 'acc-12',
    level: 3,
    is_parent: false,
  },
  {
    id: 'acc-129',
    code: '129',
    name_ar: 'مجمع إهلاك الأصول الثابتة (حساب دائن مضاد)',
    name_en: 'Accumulated Depreciation',
    account_type: 'asset',
    nature: 'credit',
    parent_id: 'acc-12',
    level: 3,
    is_parent: false,
  },

  // ── 2. الالتزامات (Liabilities) ──────────────────────────────────────────
  {
    id: 'acc-2',
    code: '2',
    name_ar: 'الالتزامات',
    name_en: 'Liabilities',
    account_type: 'liability',
    nature: 'credit',
    parent_id: null,
    level: 1,
    is_parent: true,
    is_system: true,
  },
  // 21 الالتزامات المتداولة
  {
    id: 'acc-21',
    code: '21',
    name_ar: 'الالتزامات المتداولة (قصيرة الأجل)',
    name_en: 'Current Liabilities',
    account_type: 'liability',
    nature: 'credit',
    parent_id: 'acc-2',
    level: 2,
    is_parent: true,
    is_system: true,
  },
  // 211 الموردون
  {
    id: 'acc-211',
    code: '211',
    name_ar: 'الموردون وشركات توزيع الأدوية (Accounts Payable)',
    name_en: 'Suppliers & Distributors',
    account_type: 'liability',
    nature: 'credit',
    parent_id: 'acc-21',
    level: 3,
    is_parent: true,
    is_system: true,
  },
  {
    id: 'acc-21101',
    code: '21101',
    name_ar: 'موردي وشركات توزيع الأدوية (المتحدة، ابن سينا، فارما، أوفرسيز...)',
    name_en: 'Pharma Distributors',
    account_type: 'liability',
    nature: 'credit',
    parent_id: 'acc-211',
    level: 4,
    is_parent: false,
  },
  {
    id: 'acc-21102',
    code: '21102',
    name_ar: 'موردي مستحضرات التجميل والعناية الشخصية',
    name_en: 'Cosmetics Suppliers',
    account_type: 'liability',
    nature: 'credit',
    parent_id: 'acc-211',
    level: 4,
    is_parent: false,
  },
  {
    id: 'acc-21103',
    code: '21103',
    name_ar: 'موردي المستلزمات والأجهزة والمكملات',
    name_en: 'Supplies & Devices Suppliers',
    account_type: 'liability',
    nature: 'credit',
    parent_id: 'acc-211',
    level: 4,
    is_parent: false,
  },

  // 212 الأرصدة الدائنة والمستحقات
  {
    id: 'acc-212',
    code: '212',
    name_ar: 'أرصدة دائنة ومصروفات مستحقة',
    name_en: 'Accrued Expenses & Payables',
    account_type: 'liability',
    nature: 'credit',
    parent_id: 'acc-21',
    level: 3,
    is_parent: true,
    is_system: true,
  },
  {
    id: 'acc-21201',
    code: '21201',
    name_ar: 'رواتب وأجور مستحقة للعاملين',
    name_en: 'Accrued Payroll & Salaries',
    account_type: 'liability',
    nature: 'credit',
    parent_id: 'acc-212',
    level: 4,
    is_parent: false,
  },
  {
    id: 'acc-21202',
    code: '21202',
    name_ar: 'تأمينات اجتماعية وصحية مستحقة',
    name_en: 'Accrued Social Insurance',
    account_type: 'liability',
    nature: 'credit',
    parent_id: 'acc-212',
    level: 4,
    is_parent: false,
  },
  {
    id: 'acc-21203',
    code: '21203',
    name_ar: 'ضرائب مبيعات وقيمة مضافة مستحقة',
    name_en: 'Sales Tax & VAT Payable',
    account_type: 'liability',
    nature: 'credit',
    parent_id: 'acc-212',
    level: 4,
    is_parent: false,
  },
  {
    id: 'acc-21204',
    code: '21204',
    name_ar: 'ضريبة كسب العمل والأرباح التجارية المستحقة',
    name_en: 'Income & Commercial Taxes Payable',
    account_type: 'liability',
    nature: 'credit',
    parent_id: 'acc-212',
    level: 4,
    is_parent: false,
  },
  {
    id: 'acc-213',
    code: '213',
    name_ar: 'أوراق دفع وشيكات تحت التحصيل',
    name_en: 'Notes Payable & Cheques',
    account_type: 'liability',
    nature: 'credit',
    parent_id: 'acc-21',
    level: 3,
    is_parent: false,
  },

  // 22 الالتزامات طويلة الأجل
  {
    id: 'acc-22',
    code: '22',
    name_ar: 'الالتزامات طويلة الأجل',
    name_en: 'Long-Term Liabilities',
    account_type: 'liability',
    nature: 'credit',
    parent_id: 'acc-2',
    level: 2,
    is_parent: true,
  },
  {
    id: 'acc-221',
    code: '221',
    name_ar: 'قروض وتسهيلات بنكية طويلة الأجل',
    name_en: 'Bank Loans & Facilities',
    account_type: 'liability',
    nature: 'credit',
    parent_id: 'acc-22',
    level: 3,
    is_parent: false,
  },

  // ── 3. حقوق الملكية (Equity) ─────────────────────────────────────────────
  {
    id: 'acc-3',
    code: '3',
    name_ar: 'حقوق الملكية',
    name_en: 'Equity',
    account_type: 'equity',
    nature: 'credit',
    parent_id: null,
    level: 1,
    is_parent: true,
    is_system: true,
  },
  {
    id: 'acc-31',
    code: '31',
    name_ar: 'رأس المال المدفوع',
    name_en: 'Paid-in Capital',
    account_type: 'equity',
    nature: 'credit',
    parent_id: 'acc-3',
    level: 2,
    is_parent: false,
    is_system: true,
  },
  {
    id: 'acc-32',
    code: '32',
    name_ar: 'جاري الشركاء / الملاك (سحوبات وإيداعات)',
    name_en: 'Partners / Owners Current Account',
    account_type: 'equity',
    nature: 'credit',
    parent_id: 'acc-3',
    level: 2,
    is_parent: false,
  },
  {
    id: 'acc-33',
    code: '33',
    name_ar: 'الأرباح المحتجزة / المرحلة من سنوات سابقة',
    name_en: 'Retained Earnings',
    account_type: 'equity',
    nature: 'credit',
    parent_id: 'acc-3',
    level: 2,
    is_parent: false,
    is_system: true,
  },
  {
    id: 'acc-34',
    code: '34',
    name_ar: 'صافي أرباح / خسائر العام المالي الحالي (P&L)',
    name_en: 'Current Year Earnings / Loss',
    account_type: 'equity',
    nature: 'credit',
    parent_id: 'acc-3',
    level: 2,
    is_parent: false,
    is_system: true,
  },

  // ── 4. الإيرادات (Revenues) ──────────────────────────────────────────────
  {
    id: 'acc-4',
    code: '4',
    name_ar: 'الإيرادات',
    name_en: 'Revenues',
    account_type: 'revenue',
    nature: 'credit',
    parent_id: null,
    level: 1,
    is_parent: true,
    is_system: true,
  },
  {
    id: 'acc-41',
    code: '41',
    name_ar: 'إيرادات المبيعات الصيدلانية',
    name_en: 'Pharmacy Sales Revenues',
    account_type: 'revenue',
    nature: 'credit',
    parent_id: 'acc-4',
    level: 2,
    is_parent: true,
    is_system: true,
  },
  {
    id: 'acc-411',
    code: '411',
    name_ar: 'مبيعات الأدوية البشرية',
    name_en: 'Medicines Sales',
    account_type: 'revenue',
    nature: 'credit',
    parent_id: 'acc-41',
    level: 3,
    is_parent: false,
  },
  {
    id: 'acc-412',
    code: '412',
    name_ar: 'مبيعات مستحضرات التجميل والعناية',
    name_en: 'Cosmetics Sales',
    account_type: 'revenue',
    nature: 'credit',
    parent_id: 'acc-41',
    level: 3,
    is_parent: false,
  },
  {
    id: 'acc-413',
    code: '413',
    name_ar: 'مبيعات المكملات الغذائية والفيتامينات',
    name_en: 'Supplements Sales',
    account_type: 'revenue',
    nature: 'credit',
    parent_id: 'acc-41',
    level: 3,
    is_parent: false,
  },
  {
    id: 'acc-414',
    code: '414',
    name_ar: 'مبيعات المستلزمات والأجهزة الطبية',
    name_en: 'Medical Supplies Sales',
    account_type: 'revenue',
    nature: 'credit',
    parent_id: 'acc-41',
    level: 3,
    is_parent: false,
  },
  {
    id: 'acc-419',
    code: '419',
    name_ar: 'مردودات ومسموحات المبيعات (مدين مضاد)',
    name_en: 'Sales Returns & Allowances',
    account_type: 'revenue',
    nature: 'debit',
    parent_id: 'acc-41',
    level: 3,
    is_parent: false,
  },
  {
    id: 'acc-42',
    code: '42',
    name_ar: 'إيرادات أخرى متنوعة وبونص مشتريات',
    name_en: 'Other Income & Purchase Bonuses',
    account_type: 'revenue',
    nature: 'credit',
    parent_id: 'acc-4',
    level: 2,
    is_parent: true,
  },
  {
    id: 'acc-421',
    code: '421',
    name_ar: 'خصم مكتسب وبونص شركات التوزيع (Cash Discount)',
    name_en: 'Earned Cash Discounts & Rebates',
    account_type: 'revenue',
    nature: 'credit',
    parent_id: 'acc-42',
    level: 3,
    is_parent: false,
  },
  {
    id: 'acc-422',
    code: '422',
    name_ar: 'إيرادات خدمات وتوصيل ودعاية وتأجير رفوف',
    name_en: 'Services, Delivery & Shelf-Rental Income',
    account_type: 'revenue',
    nature: 'credit',
    parent_id: 'acc-42',
    level: 3,
    is_parent: false,
  },

  // ── 5. تكلفة المبيعات (COGS) ─────────────────────────────────────────────
  {
    id: 'acc-5',
    code: '5',
    name_ar: 'تكلفة المبيعات',
    name_en: 'Cost of Goods Sold (COGS)',
    account_type: 'cogs',
    nature: 'debit',
    parent_id: null,
    level: 1,
    is_parent: true,
    is_system: true,
  },
  {
    id: 'acc-51',
    code: '51',
    name_ar: 'تكلفة مبيعات الأدوية البشرية',
    name_en: 'Medicines Cost of Sales',
    account_type: 'cogs',
    nature: 'debit',
    parent_id: 'acc-5',
    level: 2,
    is_parent: false,
  },
  {
    id: 'acc-52',
    code: '52',
    name_ar: 'تكلفة مبيعات مستحضرات التجميل',
    name_en: 'Cosmetics Cost of Sales',
    account_type: 'cogs',
    nature: 'debit',
    parent_id: 'acc-5',
    level: 2,
    is_parent: false,
  },
  {
    id: 'acc-53',
    code: '53',
    name_ar: 'تكلفة مبيعات المكملات الغذائية',
    name_en: 'Supplements Cost of Sales',
    account_type: 'cogs',
    nature: 'debit',
    parent_id: 'acc-5',
    level: 2,
    is_parent: false,
  },
  {
    id: 'acc-54',
    code: '54',
    name_ar: 'تكلفة مبيعات المستلزمات والأجهزة',
    name_en: 'Medical Supplies Cost of Sales',
    account_type: 'cogs',
    nature: 'debit',
    parent_id: 'acc-5',
    level: 2,
    is_parent: false,
  },
  {
    id: 'acc-59',
    code: '59',
    name_ar: 'تسويات عجز وهوالك وتوالف الصلاحية والأدوية منتهية الصلاحية',
    name_en: 'Inventory Shrinkage & Expired Meds',
    account_type: 'cogs',
    nature: 'debit',
    parent_id: 'acc-5',
    level: 2,
    is_parent: false,
  },

  // ── 6. المصروفات (Expenses) ──────────────────────────────────────────────
  {
    id: 'acc-6',
    code: '6',
    name_ar: 'المصروفات التشغيلية والإدارية',
    name_en: 'Expenses',
    account_type: 'expense',
    nature: 'debit',
    parent_id: null,
    level: 1,
    is_parent: true,
    is_system: true,
  },
  // 61 مصروفات الموظفين
  {
    id: 'acc-61',
    code: '61',
    name_ar: 'مصروفات الكادر الوظيفي والطبي (HR)',
    name_en: 'Payroll & Employee Expenses',
    account_type: 'expense',
    nature: 'debit',
    parent_id: 'acc-6',
    level: 2,
    is_parent: true,
    is_system: true,
  },
  {
    id: 'acc-611',
    code: '611',
    name_ar: 'رواتب وبدلات أساسية (صيادلة، مساعدين، كاشير)',
    name_en: 'Base Salaries & Allowances',
    account_type: 'expense',
    nature: 'debit',
    parent_id: 'acc-61',
    level: 3,
    is_parent: false,
  },
  {
    id: 'acc-612',
    code: '612',
    name_ar: 'مكافآت تشجيعية وعمولات التارجت',
    name_en: 'Incentives & Target Bonuses',
    account_type: 'expense',
    nature: 'debit',
    parent_id: 'acc-61',
    level: 3,
    is_parent: false,
  },
  {
    id: 'acc-613',
    code: '613',
    name_ar: 'أجور ساعات العمل الإضافي (Overtime)',
    name_en: 'Overtime Wages',
    account_type: 'expense',
    nature: 'debit',
    parent_id: 'acc-61',
    level: 3,
    is_parent: false,
  },
  {
    id: 'acc-614',
    code: '614',
    name_ar: 'حصة المنشأة في التأمينات الاجتماعية والرعاية الطبية',
    name_en: 'Social & Health Insurance Contributions',
    account_type: 'expense',
    nature: 'debit',
    parent_id: 'acc-61',
    level: 3,
    is_parent: false,
  },

  // 62 مصروفات تشغيل الفروع
  {
    id: 'acc-62',
    code: '62',
    name_ar: 'مصروفات تشغيل مقرات الصيدليات والفروع',
    name_en: 'Branch Operating Expenses',
    account_type: 'expense',
    nature: 'debit',
    parent_id: 'acc-6',
    level: 2,
    is_parent: true,
  },
  {
    id: 'acc-621',
    code: '621',
    name_ar: 'إيجار مقار الصيدليات والفروع',
    name_en: 'Branch Rent Expense',
    account_type: 'expense',
    nature: 'debit',
    parent_id: 'acc-62',
    level: 3,
    is_parent: false,
  },
  {
    id: 'acc-622',
    code: '622',
    name_ar: 'مصروفات الكهرباء والإنارة',
    name_en: 'Electricity Expense',
    account_type: 'expense',
    nature: 'debit',
    parent_id: 'acc-62',
    level: 3,
    is_parent: false,
  },
  {
    id: 'acc-623',
    code: '623',
    name_ar: 'مصروفات المياه والمرافق',
    name_en: 'Water & Utilities',
    account_type: 'expense',
    nature: 'debit',
    parent_id: 'acc-62',
    level: 3,
    is_parent: false,
  },
  {
    id: 'acc-624',
    code: '624',
    name_ar: 'مصروفات الإنترنت وخطوط الهاتف والتواصل',
    name_en: 'Internet & Telecommunications',
    account_type: 'expense',
    nature: 'debit',
    parent_id: 'acc-62',
    level: 3,
    is_parent: false,
  },
  {
    id: 'acc-625',
    code: '625',
    name_ar: 'صيانة دورية وإصلاحات وتكييفات وأجهزة',
    name_en: 'Repairs & Maintenance',
    account_type: 'expense',
    nature: 'debit',
    parent_id: 'acc-62',
    level: 3,
    is_parent: false,
  },
  {
    id: 'acc-626',
    code: '626',
    name_ar: 'أدوات نظافة ومطهرات ومهمات استهلاكية',
    name_en: 'Cleaning Supplies & Consumables',
    account_type: 'expense',
    nature: 'debit',
    parent_id: 'acc-62',
    level: 3,
    is_parent: false,
  },

  // 63 التسويق والدعاية
  {
    id: 'acc-63',
    code: '63',
    name_ar: 'مصروفات التسويق والدعاية والإعلانات',
    name_en: 'Marketing & Advertising',
    account_type: 'expense',
    nature: 'debit',
    parent_id: 'acc-6',
    level: 2,
    is_parent: false,
  },

  // 64 التوصيل والنقل
  {
    id: 'acc-64',
    code: '64',
    name_ar: 'مصروفات النقل وخدمات التوصيل (دليفري، وقود، دراجات)',
    name_en: 'Delivery & Transport Expenses',
    account_type: 'expense',
    nature: 'debit',
    parent_id: 'acc-6',
    level: 2,
    is_parent: false,
  },

  // 65 عمولات ومصروفات بنكية وخدمات الدفع الإلكتروني
  {
    id: 'acc-65',
    code: '65',
    name_ar: 'المصروفات والعمولات البنكية وخدمات الدفع الإلكتروني',
    name_en: 'Bank Fees & Electronic Payment Commissions',
    account_type: 'expense',
    nature: 'debit',
    parent_id: 'acc-6',
    level: 2,
    is_parent: true,
    is_system: true,
  },
  {
    id: 'acc-651',
    code: '651',
    name_ar: 'عمولات ومصروفات نقاط البيع (POS & Cards MDR Fees)',
    name_en: 'POS & Cards Commission',
    account_type: 'expense',
    nature: 'debit',
    parent_id: 'acc-65',
    level: 3,
    is_parent: false,
  },
  {
    id: 'acc-652',
    code: '652',
    name_ar: 'عمولات ورسوم المحافظ الإلكترونية الذكية (Wallets Fees)',
    name_en: 'Mobile Wallets Fees',
    account_type: 'expense',
    nature: 'debit',
    parent_id: 'acc-65',
    level: 3,
    is_parent: false,
  },
  {
    id: 'acc-653',
    code: '653',
    name_ar: 'رسوم وعمولات شبكة التحويل اللحظي (Instapay Transaction Fees)',
    name_en: 'Instapay Network Fees',
    account_type: 'expense',
    nature: 'debit',
    parent_id: 'acc-65',
    level: 3,
    is_parent: false,
  },
  {
    id: 'acc-654',
    code: '654',
    name_ar: 'مصاريف بنكية عامة ومصروفات كشوف الحساب والدمغات',
    name_en: 'General Banking Fees & Stamp Duties',
    account_type: 'expense',
    nature: 'debit',
    parent_id: 'acc-65',
    level: 3,
    is_parent: false,
  },

  // 66 مصروفات إدارية وعمومية
  {
    id: 'acc-66',
    code: '66',
    name_ar: 'مصروفات إدارية وعمومية (برمجيات، ضيافة، استشارات)',
    name_en: 'General & Administrative Expenses',
    account_type: 'expense',
    nature: 'debit',
    parent_id: 'acc-6',
    level: 2,
    is_parent: false,
  },
];

export const DEFAULT_COST_CENTERS = [
  { id: 'cc-1', code: 'CC-001', name: 'صيدلية سموحة', branch_id: '1', is_active: true },
  { id: 'cc-2', code: 'CC-002', name: 'صيدلية العجمي', branch_id: '2', is_active: true },
  { id: 'cc-3', code: 'CC-003', name: 'صيدلية محطة الرمل', branch_id: '3', is_active: true },
  { id: 'cc-4', code: 'CC-004', name: 'المخزن الرئيسي للمجموعة', branch_id: null, is_active: true },
  { id: 'cc-5', code: 'CC-005', name: 'الإدارة العامة والمكتب التنفيذي', branch_id: null, is_active: true },
];

export const DEFAULT_TREASURIES = [
  {
    id: 'tr-1',
    code: 'TR-01',
    name: 'خزينة الإدارة الرئيسية (كاش)',
    treasury_type: 'cashbox',
    branch_id: null,
    account_id: 'acc-11101',
    fee_percentage: 0.0,
    fee_fixed: 0.0,
    commission_account_id: null,
    current_balance: 0,
    is_active: true,
  },
  {
    id: 'tr-2',
    code: 'TR-02',
    name: 'خزينة صيدلية سموحة (كاش)',
    treasury_type: 'cashbox',
    branch_id: '1',
    account_id: 'acc-11102',
    fee_percentage: 0.0,
    fee_fixed: 0.0,
    commission_account_id: null,
    current_balance: 0,
    is_active: true,
  },
  {
    id: 'tr-3',
    code: 'TR-03',
    name: 'خزينة صيدلية العجمي (كاش)',
    treasury_type: 'cashbox',
    branch_id: '2',
    account_id: 'acc-11103',
    fee_percentage: 0.0,
    fee_fixed: 0.0,
    commission_account_id: null,
    current_balance: 0,
    is_active: true,
  },
  {
    id: 'tr-4',
    code: 'TR-04',
    name: 'خزينة صيدلية محطة الرمل (كاش)',
    treasury_type: 'cashbox',
    branch_id: '3',
    account_id: 'acc-11104',
    fee_percentage: 0.0,
    fee_fixed: 0.0,
    commission_account_id: null,
    current_balance: 0,
    is_active: true,
  },
  {
    id: 'tr-5',
    code: 'TR-05',
    name: 'البنك الأهلي المصري (حساب رئيسي)',
    treasury_type: 'bank',
    branch_id: null,
    account_id: 'acc-11201',
    fee_percentage: 0.0,
    fee_fixed: 0.0,
    commission_account_id: 'acc-654',
    current_balance: 0,
    is_active: true,
  },
  {
    id: 'tr-6',
    code: 'TR-06',
    name: 'أجهزة نقاط البيع (POS - فيزا / ماستركارد)',
    treasury_type: 'pos',
    branch_id: null,
    account_id: 'acc-11301',
    fee_percentage: 1.5, // 1.50% خصم البنك لبطاقات الائتمان
    fee_fixed: 0.0,
    commission_account_id: 'acc-651',
    current_balance: 0,
    is_active: true,
  },
  {
    id: 'tr-7',
    code: 'TR-07',
    name: 'شبكة التحويل اللحظي (Instapay)',
    treasury_type: 'instapay',
    branch_id: null,
    account_id: 'acc-11302',
    fee_percentage: 0.5, // 0.50% رسوم تحويل لحظي
    fee_fixed: 0.0,
    commission_account_id: 'acc-653',
    current_balance: 0,
    is_active: true,
  },
  {
    id: 'tr-8',
    code: 'TR-08',
    name: 'محافظ الهاتف الذكي (فودافون كاش / أورنج كاش)',
    treasury_type: 'wallet',
    branch_id: null,
    account_id: 'acc-11303',
    fee_percentage: 1.0, // 1.00% رسوم سحب/تحويل المحافظ
    fee_fixed: 1.0,
    commission_account_id: 'acc-652',
    current_balance: 0,
    is_active: true,
  },
];
