/**
 * defaultPharmaVendors.js
 * بيانات شركات توزيع الأدوية والموردين المعتمدة وسجلات فواتير المشتريات والسداد
 */

export const DEFAULT_PHARMA_VENDORS = [
  {
    id: 'vnd-001',
    code: 'VND-101',
    account_code: '21101',
    name_ar: 'الشركة المتحدة للصيادلة (UCP)',
    name_en: 'United Company of Pharmacists',
    category: 'pharma_distributor',
    phone: '19696',
    rep_name: 'أ. حسام فوزي (المندوب التجاري)',
    rep_phone: '01001234567',
    credit_days: 45,
    credit_limit: 500000,
    current_balance: 145200.50, // رصيد دائن للمورد
    notes: 'التوريد اليومي الرئيسي للأدوية والمحاليل - خصم تجاري إضافي 1.5%',
  },
  {
    id: 'vnd-002',
    code: 'VND-102',
    account_code: '21101',
    name_ar: 'شركة ابن سينا فارما (Ibnsina Pharma)',
    name_en: 'Ibnsina Pharma',
    category: 'pharma_distributor',
    phone: '16440',
    rep_name: 'أ. محمود طارق',
    rep_phone: '01119876543',
    credit_days: 60,
    credit_limit: 450000,
    current_balance: 88450.00,
    notes: 'طلبيات الأدوية المستوردة وأدوية الثلاجة والألبان',
  },
  {
    id: 'vnd-003',
    code: 'VND-103',
    account_code: '21101',
    name_ar: 'شركة فارما أوفرسيز (Pharma Overseas)',
    name_en: 'Pharma Overseas',
    category: 'pharma_distributor',
    phone: '16688',
    rep_name: 'د. سامح عبد العزيز',
    rep_phone: '01223344556',
    credit_days: 30,
    credit_limit: 300000,
    current_balance: 42100.00,
    notes: 'أدوية علاجية وأمراض مزمنة وأنسولين',
  },
  {
    id: 'vnd-004',
    code: 'VND-104',
    account_code: '21101',
    name_ar: 'شركة رامكو فارما (Ramco Pharma)',
    name_en: 'Ramco Pharma',
    category: 'pharma_distributor',
    phone: '02-24185200',
    rep_name: 'أ. كريم جلال',
    rep_phone: '01099887766',
    credit_days: 45,
    credit_limit: 250000,
    current_balance: 31800.75,
    notes: 'مكملات غذائية وفيتامينات وقطرات عيون',
  },
  {
    id: 'vnd-005',
    code: 'VND-105',
    account_code: '21101',
    name_ar: 'الشركة المصرية لتجارة الأدوية',
    name_en: 'Egyptian Drug Trading Co.',
    category: 'pharma_distributor',
    phone: '19455',
    rep_name: 'د. نبيل الشامي',
    rep_phone: '01066554433',
    credit_days: 15,
    credit_limit: 150000,
    current_balance: 19500.00,
    notes: 'أدوية الطوارئ وألبان الأطفال المدعمة ومناقصات التأمين',
  },
  {
    id: 'vnd-006',
    code: 'VND-201',
    account_code: '21102',
    name_ar: 'شركة لوريال باريس لمستحضرات التجميل',
    name_en: 'L\'Oréal Cosmeceuticals Egypt',
    category: 'cosmetics_supplier',
    phone: '02-27351000',
    rep_name: 'أ. مروة كمال',
    rep_phone: '01287654321',
    credit_days: 60,
    credit_limit: 200000,
    current_balance: 64200.00,
    notes: 'مستحضرات التجميل والعناية بالبشرة (La Roche-Posay, CeraVe, Vichy)',
  },
];

export const DEFAULT_VENDOR_TRANSACTIONS = [
  {
    id: 'vtx-001',
    vendor_id: 'vnd-001',
    tx_type: 'invoice', // invoice | payment | credit_note (expired return)
    tx_number: 'INV-2026-9011',
    tx_date: '2026-09-02',
    due_date: '2026-10-17',
    branch_id: 'br-1',
    amount: 54300.00,
    payment_method: 'credit', // credit | cash | cheque | bank_transfer
    cheque_number: '',
    status: 'open',
    narration: 'فاتورة مشتريات أدوية ومحاليل علاجية لشهر سبتمبر - صيدلية سموحة',
  },
  {
    id: 'vtx-002',
    vendor_id: 'vnd-001',
    tx_type: 'payment',
    tx_number: 'PAY-2026-084',
    tx_date: '2026-09-04',
    due_date: '',
    branch_id: '',
    amount: 35000.00,
    payment_method: 'cheque',
    cheque_number: 'CHQ-884912',
    status: 'completed',
    narration: 'سداد شيك بنك مصر رقم 884912 لصالح شركة المتحدة للصيادلة',
  },
  {
    id: 'vtx-003',
    vendor_id: 'vnd-001',
    tx_type: 'credit_note',
    tx_number: 'CRN-2026-019',
    tx_date: '2026-09-05',
    due_date: '',
    branch_id: 'br-1',
    amount: 3850.00,
    payment_method: 'credit_adjustment',
    cheque_number: '',
    status: 'completed',
    narration: 'إشعار خصم مرتجع أدوية منتهية الصلاحية (إكسباير) معتمد من الموزع',
  },
  {
    id: 'vtx-004',
    vendor_id: 'vnd-002',
    tx_type: 'invoice',
    tx_number: 'INV-IBN-8742',
    tx_date: '2026-09-03',
    due_date: '2026-11-03',
    branch_id: 'br-2',
    amount: 42100.00,
    payment_method: 'credit',
    cheque_number: '',
    status: 'open',
    narration: 'فاتورة أدوية مستوردة وثلاجة - صيدلية العجمي',
  },
  {
    id: 'vtx-005',
    vendor_id: 'vnd-006',
    tx_type: 'invoice',
    tx_number: 'INV-LOR-339',
    tx_date: '2026-09-01',
    due_date: '2026-11-01',
    branch_id: 'br-3',
    amount: 32000.00,
    payment_method: 'credit',
    cheque_number: '',
    status: 'open',
    narration: 'توريد منتجات سيرافي وفيشي لاروش بوزيه - صيدلية محطة الرمل',
  },
];
