/**
 * defaultPharmaVendors.js
 * بيانات شركات توزيع الأدوية والموردين المعتمدة
 * تم تصفير جميع الأرصدة الافتراضية والمعاملات لتشغيل النظام نظيفاً 100%
 */

export const DEFAULT_PHARMA_VENDORS = [
  {
    id: 'vnd-001',
    code: 'VND-101',
    account_code: '21101',
    name_ar: 'الشركة المتحدة للصيادلة (UCP)',
    name_en: 'United Company of Pharmacists',
    category: 'pharma_distributor',
    phone: '19696',
    rep_name: 'المندوب التجاري',
    rep_phone: '',
    credit_days: 45,
    credit_limit: 500000,
    current_balance: 0,
    notes: 'التوريد اليومي للأدوية والمحاليل',
  },
  {
    id: 'vnd-002',
    code: 'VND-102',
    account_code: '21101',
    name_ar: 'شركة ابن سينا فارما (Ibnsina Pharma)',
    name_en: 'Ibnsina Pharma',
    category: 'pharma_distributor',
    phone: '16440',
    rep_name: 'المندوب التجاري',
    rep_phone: '',
    credit_days: 60,
    credit_limit: 450000,
    current_balance: 0,
    notes: 'طلبيات الأدوية المستوردة وأدوية الثلاجة والألبان',
  },
  {
    id: 'vnd-003',
    code: 'VND-103',
    account_code: '21101',
    name_ar: 'شركة فارما أوفرسيز (Pharma Overseas)',
    name_en: 'Pharma Overseas',
    category: 'pharma_distributor',
    phone: '16688',
    rep_name: 'المندوب التجاري',
    rep_phone: '',
    credit_days: 30,
    credit_limit: 300000,
    current_balance: 0,
    notes: 'أدوية علاجية وأمراض مزمنة وأنسولين',
  },
  {
    id: 'vnd-004',
    code: 'VND-104',
    account_code: '21101',
    name_ar: 'شركة رامكو فارما (Ramco Pharma)',
    name_en: 'Ramco Pharma',
    category: 'pharma_distributor',
    phone: '02-24185200',
    rep_name: 'المندوب التجاري',
    rep_phone: '',
    credit_days: 45,
    credit_limit: 250000,
    current_balance: 0,
    notes: 'مكملات غذائية وفيتامينات وقطرات عيون',
  },
  {
    id: 'vnd-005',
    code: 'VND-105',
    account_code: '21101',
    name_ar: 'الشركة المصرية لتجارة الأدوية',
    name_en: 'Egyptian Drug Trading Co.',
    category: 'pharma_distributor',
    phone: '19455',
    rep_name: 'المندوب التجاري',
    rep_phone: '',
    credit_days: 15,
    credit_limit: 150000,
    current_balance: 0,
    notes: 'أدوية الطوارئ وألبان الأطفال ومناقصات التأمين',
  },
  {
    id: 'vnd-006',
    code: 'VND-201',
    account_code: '21102',
    name_ar: 'شركة لوريال باريس لمستحضرات التجميل',
    name_en: 'L\'Oréal Cosmeceuticals Egypt',
    category: 'cosmetics_supplier',
    phone: '02-27351000',
    rep_name: 'المندوب التجاري',
    rep_phone: '',
    credit_days: 60,
    credit_limit: 200000,
    current_balance: 0,
    notes: 'مستحضرات التجميل والعناية بالبشرة',
  },
];

// مصفوفة المعاملات الافتراضية فارغة للتشغيل الحقيقي النظيف
export const DEFAULT_VENDOR_TRANSACTIONS = [];
